# Generated by Django 3.2 on 2023-01-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0003_alter_yamuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamuser',
            name='confirmation_code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
