# Generated by Django 3.2 on 2023-01-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlegenre',
            options={'verbose_name': 'Произведение и жанр', 'verbose_name_plural': 'Произведения и жанр'},
        ),
    ]
